(clear)
(load 0_Main.clp)
(load 1_Env.clp)
(load Mappe/sparse_molto.clp)
(load 2_Agent.clp)
(load 3_AgentCellBaseInference.clp)
(load 4_AgentDecision_standard.clp)
(reset)
(run)
(dribble-on output.txt)
(focus ENV)
(facts)
(dribble-off)
